version: '3.8'

services:
  vpn-client:
    image: ghcr.io/tsuzu/l2tp-ipsec-proxy:latest
    env_file:
      - ./vpn.env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/ppp
    privileged: true
    restart: unless-stopped
    ports:
      - "8080:8080"  # HTTP proxy
      - "1080:1080"  # SOCKS proxy
    # network_mode: host is faster, but routing table on host will be changed
    volumes:
      - /lib/modules:/lib/modules:ro
